# Generated by Django 4.2.7 on 2025-11-21 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('posts', '0001_initial'),
        ('users', '0001_initial'),
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationactioncomment',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moderationactionpost',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moderationactioncomment',
            name='action',
            field=models.CharField(choices=[('delete', 'Eliminar'), ('hide', 'Ocultar'), ('warn', 'Advertencia'), ('approve', 'Aprobar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='moderationactioncomment',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_moderation_actions', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='moderationactioncomment',
            name='target_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='moderationactionpost',
            name='action',
            field=models.CharField(choices=[('delete', 'Eliminar'), ('hide', 'Ocultar'), ('warn', 'Advertencia'), ('approve', 'Aprobar'), ('pin', 'Fijar'), ('unpin', 'Desfijar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='moderationactionpost',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_moderation_actions', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='moderationactionpost',
            name='target_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='reportcomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='reportcomment',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reports', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reports', to='users.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='reportcomment',
            unique_together={('reporter', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='reportpost',
            unique_together={('reporter', 'post')},
        ),
    ]
