# Generated by Django 4.2.7 on 2025-12-04 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_avatar'),
        ('moderation', '0002_moderationactioncomment_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcomment',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcomment',
            name='category',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Acoso'), ('inappropriate', 'Contenido inapropiado'), ('misinformation', 'Información falsa'), ('other', 'Otro')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='reportcomment',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcomment',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_comment_reports', to='users.profile'),
        ),
        migrations.AddField(
            model_name='reportcomment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('reviewed', 'Revisado'), ('resolved', 'Resuelto'), ('dismissed', 'Desestimado')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='reportpost',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportpost',
            name='category',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Acoso'), ('inappropriate', 'Contenido inapropiado'), ('misinformation', 'Información falsa'), ('other', 'Otro')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='reportpost',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportpost',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_post_reports', to='users.profile'),
        ),
        migrations.AddField(
            model_name='reportpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('reviewed', 'Revisado'), ('resolved', 'Resuelto'), ('dismissed', 'Desestimado')], default='pending', max_length=20),
        ),
    ]
