# Generated by Django 4.2.7 on 2025-12-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_reportcomment_admin_notes_reportcomment_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationactioncomment',
            name='action',
            field=models.CharField(choices=[('delete', 'Eliminar'), ('hide', 'Ocultar'), ('warn', 'Advertencia'), ('approve', 'Aprobar'), ('review', 'Revisar'), ('dismiss', 'Desestimar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='moderationactionpost',
            name='action',
            field=models.CharField(choices=[('delete', 'Eliminar'), ('hide', 'Ocultar'), ('warn', 'Advertencia'), ('approve', 'Aprobar'), ('pin', 'Fijar'), ('unpin', 'Desfijar'), ('review', 'Revisar'), ('dismiss', 'Desestimar')], max_length=20),
        ),
    ]
