# Generated by Django 4.2.7 on 2025-11-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmedia',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'Post Media', 'verbose_name_plural': 'Post Media'},
        ),
        migrations.RemoveField(
            model_name='postmedia',
            name='file',
        ),
        migrations.AddField(
            model_name='postmedia',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Imagen'), ('video', 'Video'), ('audio', 'Audio')], max_length=10, null=True),
        ),
    ]
