# Generated by Django 4.2.7 on 2025-12-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmedia',
            name='file',
        ),
        migrations.AddField(
            model_name='commentmedia',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commentmedia',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commentmedia',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commentmedia',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commentmedia',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Imagen'), ('video', 'Video'), ('audio', 'Audio')], max_length=10, null=True),
        ),
    ]
