# Generated by Django 4.2.7 on 2025-12-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('suspendido', 'Suspendido'), ('baneado', 'Baneado')], default='normal', max_length=20),
        ),
    ]
